-- AmarMart Oracle Schema (Oracle 11g XE)
-- Run: sqlplus amarmart/AmarMart123@localhost:1521/XE @database/oracle/01_schema.sql

WHENEVER SQLERROR CONTINUE

BEGIN EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE migrations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE users_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE products_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE orders_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE order_items_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE invoice_no_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_users_bi'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_products_bi'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_orders_bi'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_order_items_bi'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_orders_invoice'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_reduce_stock'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_total_revenue'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_dashboard_stats'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE products_id_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE orders_id_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE order_items_id_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE invoice_no_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE users (
    id NUMBER(19) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR2(255) NOT NULL,
    is_admin NUMBER(1) DEFAULT 0 NOT NULL,
    remember_token VARCHAR2(100) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT users_email_uk UNIQUE (email)
);

CREATE TABLE products (
    id NUMBER(19) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    slug VARCHAR2(255) NOT NULL,
    description CLOB NULL,
    price NUMBER(12,2) DEFAULT 0 NOT NULL,
    stock NUMBER(10) DEFAULT 0 NOT NULL,
    image VARCHAR2(255) NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT products_slug_uk UNIQUE (slug)
);

CREATE TABLE orders (
    id NUMBER(19) PRIMARY KEY,
    invoice_number VARCHAR2(30) NULL,
    customer_name VARCHAR2(255) NOT NULL,
    customer_email VARCHAR2(255) NOT NULL,
    customer_phone VARCHAR2(50) NOT NULL,
    customer_address VARCHAR2(1000) NOT NULL,
    total_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(30) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT orders_invoice_uk UNIQUE (invoice_number)
);

CREATE TABLE order_items (
    id NUMBER(19) PRIMARY KEY,
    order_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    product_name VARCHAR2(255) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    subtotal NUMBER(12,2) NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT order_items_order_fk FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_items_product_fk FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE migrations (
    id NUMBER(10) PRIMARY KEY,
    migration VARCHAR2(255) NOT NULL,
    batch NUMBER(10) NOT NULL
);

CREATE SEQUENCE migrations_id_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER trg_migrations_bi
BEFORE INSERT ON migrations
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT migrations_id_seq.NEXTVAL INTO :NEW.id FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_users_bi
BEFORE INSERT ON users
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT users_id_seq.NEXTVAL INTO :NEW.id FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_products_bi
BEFORE INSERT ON products
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT products_id_seq.NEXTVAL INTO :NEW.id FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_orders_bi
BEFORE INSERT ON orders
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT orders_id_seq.NEXTVAL INTO :NEW.id FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_order_items_bi
BEFORE INSERT ON order_items
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT order_items_id_seq.NEXTVAL INTO :NEW.id FROM dual;
END;
/

PROMPT Schema tables and ID triggers created.
EXIT;
