-- AmarMart Oracle PL/SQL
-- Run: sqlplus amarmart/AmarMart123@localhost:1521/XE @database/oracle/02_plsql.sql

WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Invoice number generated by Oracle Trigger (not Laravel)
CREATE OR REPLACE TRIGGER trg_orders_invoice
BEFORE INSERT ON orders
FOR EACH ROW
DECLARE
    v_seq NUMBER;
BEGIN
    IF :NEW.invoice_number IS NULL THEN
        SELECT invoice_no_seq.NEXTVAL INTO v_seq FROM dual;
        :NEW.invoice_number := 'INV-' || LPAD(TO_CHAR(v_seq), 6, '0');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invoice generation failed: ' || SQLERRM);
END;
/

-- Stock reduction happens inside Oracle Trigger when order item is inserted
CREATE OR REPLACE TRIGGER trg_reduce_stock
BEFORE INSERT ON order_items
FOR EACH ROW
DECLARE
    v_stock products.stock%TYPE;
    e_insufficient EXCEPTION;
BEGIN
    SELECT stock INTO v_stock
    FROM products
    WHERE id = :NEW.product_id
    FOR UPDATE;

    IF v_stock < :NEW.quantity THEN
        RAISE e_insufficient;
    END IF;

    UPDATE products
    SET stock = stock - :NEW.quantity,
        updated_at = SYSTIMESTAMP
    WHERE id = :NEW.product_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Product not found for stock reduction.');
    WHEN e_insufficient THEN
        RAISE_APPLICATION_ERROR(-20003, 'Insufficient stock for product ID ' || :NEW.product_id);
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004, 'Stock reduction failed: ' || SQLERRM);
END;
/

-- Revenue calculation must use Oracle Function
CREATE OR REPLACE FUNCTION fn_total_revenue (
    p_status IN VARCHAR2 DEFAULT NULL
) RETURN NUMBER
IS
    v_total NUMBER(12,2) := 0;
BEGIN
    SELECT NVL(SUM(total_amount), 0)
    INTO v_total
    FROM orders
    WHERE (p_status IS NULL OR status = p_status)
      AND status <> 'cancelled';

    RETURN v_total;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END fn_total_revenue;
/

-- Dashboard statistics must use Oracle Procedure
CREATE OR REPLACE PROCEDURE sp_dashboard_stats (
    p_total_products OUT NUMBER,
    p_total_orders   OUT NUMBER,
    p_total_revenue  OUT NUMBER,
    p_low_stock      OUT NUMBER,
    p_pending_orders OUT NUMBER
)
IS
BEGIN
    SELECT COUNT(*) INTO p_total_products FROM products;
    SELECT COUNT(*) INTO p_total_orders FROM orders;
    p_total_revenue := fn_total_revenue(NULL);
    SELECT COUNT(*) INTO p_low_stock FROM products WHERE stock <= 5 AND is_active = 1;
    SELECT COUNT(*) INTO p_pending_orders FROM orders WHERE status = 'pending';
EXCEPTION
    WHEN OTHERS THEN
        p_total_products := 0;
        p_total_orders := 0;
        p_total_revenue := 0;
        p_low_stock := 0;
        p_pending_orders := 0;
        RAISE_APPLICATION_ERROR(-20005, 'Dashboard stats failed: ' || SQLERRM);
END sp_dashboard_stats;
/

PROMPT PL/SQL objects created successfully.
EXIT;
