<?php $__env->startSection('title', 'Invoice '.$order->invoice_number); ?>

<?php $__env->startSection('content'); ?>
<div class="border p-4">
    <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
            <div class="display-6">AmarMart</div>
            <div class="text-muted">Sales Invoice</div>
        </div>
        <div class="text-end">
            <div><strong>Invoice:</strong> <?php echo e($order->invoice_number); ?></div>
            <div><strong>Date:</strong> <?php echo e(optional($order->created_at)->format('Y-m-d H:i')); ?></div>
            <div><strong>Status:</strong> <?php echo e(ucfirst($order->status)); ?></div>
        </div>
    </div>

    <div class="mb-4">
        <h2 class="h5">Bill To</h2>
        <div><?php echo e($order->customer_name); ?></div>
        <div><?php echo e($order->customer_email); ?></div>
        <div><?php echo e($order->customer_phone); ?></div>
        <div><?php echo e($order->customer_address); ?></div>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Item</th>
            <th>Unit Price</th>
            <th>Qty</th>
            <th>Subtotal</th>
        </tr>
        </thead>
        <tbody>
        <?php $__currentLoopData = $order->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($index + 1); ?></td>
                <td><?php echo e($item->product_name); ?></td>
                <td>BDT <?php echo e(number_format($item->unit_price, 2)); ?></td>
                <td><?php echo e($item->quantity); ?></td>
                <td>BDT <?php echo e(number_format($item->subtotal, 2)); ?></td>
            </tr>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4" class="text-end">Total</th>
            <th>BDT <?php echo e(number_format($order->total_amount, 2)); ?></th>
        </tr>
        </tfoot>
    </table>

    <p class="small text-muted mb-0">Invoice number generated by Oracle trigger. Stock reduced by Oracle trigger.</p>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.print', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH H:\Girhub local\AmarMart_Final_Project\resources\views/shop/invoice/show.blade.php ENDPATH**/ ?>