@extends('layouts.print')

@section('title', 'Invoice '.$order->invoice_number)

@section('content')
<div class="border p-4">
    <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
            <div class="display-6">AmarMart</div>
            <div class="text-muted">Sales Invoice</div>
        </div>
        <div class="text-end">
            <div><strong>Invoice:</strong> {{ $order->invoice_number }}</div>
            <div><strong>Date:</strong> {{ optional($order->created_at)->format('Y-m-d H:i') }}</div>
            <div><strong>Status:</strong> {{ ucfirst($order->status) }}</div>
        </div>
    </div>

    <div class="mb-4">
        <h2 class="h5">Bill To</h2>
        <div>{{ $order->customer_name }}</div>
        <div>{{ $order->customer_email }}</div>
        <div>{{ $order->customer_phone }}</div>
        <div>{{ $order->customer_address }}</div>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Item</th>
            <th>Unit Price</th>
            <th>Qty</th>
            <th>Subtotal</th>
        </tr>
        </thead>
        <tbody>
        @foreach($order->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->product_name }}</td>
                <td>BDT {{ number_format($item->unit_price, 2) }}</td>
                <td>{{ $item->quantity }}</td>
                <td>BDT {{ number_format($item->subtotal, 2) }}</td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>
            <th colspan="4" class="text-end">Total</th>
            <th>BDT {{ number_format($order->total_amount, 2) }}</th>
        </tr>
        </tfoot>
    </table>

    <p class="small text-muted mb-0">Invoice number generated by Oracle trigger. Stock reduced by Oracle trigger.</p>
</div>
@endsection
